using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BettyDialogueTrigger : MonoBehaviour
{
    // Start is called before the first frame update
    public MissionManager missionManager;
    private Dialogue dialogueScript;

    void Start()
    {
        dialogueScript = GetComponent<Dialogue>();
    }

    void Update()
    {
        // Solo permitir hablar si ya habl칩 con Jamel
        if (missionManager.currentState == MissionManager.MissionState.TalkedToJamel)
        {
            dialogueScript.enabled = true;
        }
        else
        {
            dialogueScript.enabled = false;
        }

        // Si el di치logo termin칩, completar la misi칩n
        if (!dialogueScript.isActiveAndEnabled && missionManager.currentState == MissionManager.MissionState.TalkedToJamel)
        {
            missionManager.TalkedToBetty();
        }
    }
}
